api_platform:
    title: API Platform's demo
    version: 1.0.0
    description: |
        This is a demo application of the [API Platform](https://api-platform.com) framework.
        [Its source code](https://github.com/api-platform/demo) includes various examples, check it out!
        You may also be interested by [the GraphQL entrypoint](/graphql).
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    formats:
        json: ['application/json']
        html: ['text/html']
    http_cache:
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization', 'Origin']
        public: true
    collection:
        pagination:
            items_per_page: 30