nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(FRONT_HOST)%', '^http://localhost:[0-9]+']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+', '%env(FRONT_HOST)%', '*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_headers: ['*']
            max_age: 3600