imports:
#  - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
#  - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
#  - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }
#  - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }

parameters:
  sylius_core.public_dir: "%kernel.project_dir%/public"
  sylius.cache:
    type: array
#
#sylius_user:
#  driver: doctrine/orm
#  resources:
#    admin:
#      user:
#        classes:
#          model: App\Entity\User\AdminUser
#    shop:
#      user:
#        classes:
#          model: App\Entity\User\ShopUser
#    oauth:
#      user:
#        classes:
#          model: App\Entity\User\UserOAuth
