#sylius_customer:
#  driver: doctrine/orm
#  resources:
#    customer:
#      classes:
#        model: Sylius\Component\Core\Model\Customer
#        repository: Sylius\Bundle\CoreBundle\Doctrine\ORM\CustomerRepository
#        interface: Sylius\Component\Customer\Model\CustomerInterface
#        controller: App\Controller\User\CustomerController
#        factory: Sylius\Component\Resource\Factory\Factoryz
#    customer_group:
#      classes:
#        model: Sylius\Component\Customer\Model\CustomerGroup
#        interface: Sylius\Component\Customer\Model\CustomerGroupInterface
#        controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
#        factory: Sylius\Component\Resource\Factory\Factory
#        form: Sylius\Bundle\CustomerBundle\Form\Type\CustomerGroupType
