# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '3.1'
services:

  mysql:
    image: percona:5.7
    command: 
      - --disable-partition-engine-check
      - --innodb_use_native_aio=0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      # - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
       - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    ports:
      - "3306:3306"
      
  # mysql:
  #   image: mysql:5.7
  #   container_name: sf4_mysql
  #   command: mysqld --initialize-insecure
  #   volumes:
  #     - .docker/data/db:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    image: php:7.2-cli
    container_name: sf4_php
    volumes:
      - ${SYMFONY_APP}:/home/wwwroot/sf4
    environment:
      - maildev_host=sf4_maildev
    depends_on:
      - maildev
      - mysql
    ports:
      - 8000:8000
    command: "cd public && php -S localhost:8000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf4_phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql

  maildev:
    image: djfarrelly/maildev
    container_name: sf4_maildev
    ports:
      - 8001:80

  node:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./front:/home/node/app
    ports:
      - 4200:4200
    expose:
      - 4200
    command: yarn start