# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: "3.4"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build: .docker/php
    working_dir: /home/wwwroot/sf4
    volumes:
      - ./back:/home/wwwroot/sf4
      - .docker/php/php.ini:/usr/local/etc/php/php.ini:rw
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.52
      PHP_IDE_CONFIG: "serverName=back.local"
    depends_on:
      - maildev
      - mysql

  apache:
    build: .docker/apache
    ports:
      - 8000:80
    volumes:
      - .docker/apache/vhosts:/etc/apache2/sites-enabled
      - ./back:/home/wwwroot/sf4
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql

  maildev:
    image: djfarrelly/maildev
    container_name: sf4_maildev
    ports:
      - 8001:80

  node:
    image: "node:12.13.1"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./front:/home/node/app
    ports:
      - 4200:4200
    command: yarn start
